data_path: "./dataset"

visualization_config:
    dispaly_freq: 1 # unit: iteration

train_hypernet_config:
    seed: 42
    lr: 0.00375
    train_batch_size: 1024
    val_batch_size: 2048
    epoch: 500
    save_freq: 10 # unit: epoch
    checkpoint_path: "./checkpoint"
    
    