data_path: "./dataset"
seed: 42

visualization_config:
    display_freq: 1 # unit: iteration

train_hypernet_config:
    model: "small"
    loss: "CE" # "LSCE"|"CE"
    lr: 0.00375
    train_batch_size: 1024
    val_batch_size: 2048
    epoch: 300
    save_freq: 10 # unit: epoch
    checkpoint_path: "./checkpoint"


val_hypernet_config:
    checkpoint_filepath: "./checkpoint/hypernet/hypernet_500.pth"


search_config:
    val_batch_size: 2500
    checkpoint_filepath: "./checkpoint/hypernet/hypernet_500.pth"
    
    