---
# data_path: "./dataset" # for cifar100
data_path: "/workspace/data/imagenet"
seed: 42

visualization_config:
    display_freq: 1 # unit: iteration

train_hypernet_config:
    model: "large"
    # dataset: "cifar100"
    dataset: "imagenet"
    loss: "LSCE" # "LSCE"|"CE"
    lr: 0.035
    train_batch_size: 512
    epoch: 32
    dropfc_rate: 0.5
    weight_decay: 0.00001
    num_workers: 4
    save_freq: 1 # unit: epoch
    checkpoint_path: "./checkpoint/hypernet"


val_hypernet_config:
    val_batch_size: 2048
    checkpoint_filepath: "./checkpoint/hypernet/hypernet_32.pth"


search_config:
    model: 'large'
    dataset: "imagenet"
    val_batch_size: 2500
    num_workers: 4
    checkpoint_filepath: "./checkpoint/hypernet/hypernet_32.pth"



train_config:
    dataset: "cifar100"
    loss: "LSCE" # "LSCE"|"CE"
    lr: 0.0350
    train_batch_size: 256
    epoch: 100
    dropfc_rate: 0.5
    # start_dropblock_rate: 0
    # end_dropblock_rate: 0.15
    # dropblock_schedule_steps: -1 # -1 means =epoch
    weight_decay: 0.00006
    num_workers: 2
    save_freq: 100 # unit: epoch
    checkpoint_path: "./checkpoint/moga_large"

val_config:
    val_batch_size: 2048
    checkpoint_filepath: "./checkpoint/moga_large/hypernet_500.pth"
    
    