---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    mplog:
        class: mplog.MultiProcessingLog
        level: DEBUG
        formatter: simple
        filename: mplog.log
        mode: w
root:
    level: DEBUG
    handlers:
        # - console
        - mplog